### ISSUE TITLE
Incorrect ~rots rotation

### ISSUE THREAD

**Issue by Phillipluck** [WittyPleb/RuneCord#1]
Using the ~rots function displays the wrong rotation. It has been wrong the past 3 days when I check.

July 1st rotation (in-game):
![screen shot 2016-07-01 at 12 50 43 pm](https://cloud.githubusercontent.com/assets/20248123/16533013/b245bb54-3f8a-11e6-8a78-c0de65247d8e.png)

Discord rotation: 
![screen shot 2016-07-01 at 12 48 56 pm](https://cloud.githubusercontent.com/assets/20248123/16533027/c733710a-3f8a-11e6-86f0-ca1dee297ddb.png)

**Comment by WittyPleb** [comment]
Thank you for reporting this, issue has be resolved.
