### ISSUE TITLE
OldSchool Stats Not Working

### ISSUE THREAD

**Issue by sudonate91** [WittyPleb/RuneCord#15]
Old School stats no longer come back from ~osstats command

**Reproduction Steps:**

1. type ~osstats supernate91

**Expected behavior:**

Bring back stats from the old school server for supernate91

**Observed behavior:**
Nothing happens

**Screenshots and GIFs**
![screen shot 2016-11-11 at 8 05 17 am](https://cloud.githubusercontent.com/assets/9617274/20217476/b0893426-a7e5-11e6-8081-9418b3715b1a.png)

**Bot version:** v3.2.0
**Local or Official:** Official

**Additional information:**

* Problem started happening recently, didn't happen in an older version of RuneCord: [Yes]. I didnt update anything
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by WittyPleb** [comment]
As of v3.2.0 the bot no longer supports Old School. Sorry.
