### ISSUE TITLE
Program wont run

### ISSUE THREAD

**Issue by cshunton** [WittyPleb/RuneCord#18]
I love this program, when I downloaded it and installed all of the required files. I edited the config and tried to run the program and this is what it says:

http://prntscr.com/di7c5d

**Comment by WittyPleb** [comment]
I need more information to properly help you with this.

What operating system are you using?
What NodeJS version are you using?
What `npm` version are you using?
Have you ran `npm install`?

Also, sorry for the long wait, I've been busy with the holidays.

**Comment by WittyPleb** [comment]
Hasn't responded in nearly 30 days. Closing.
