### ISSUE TITLE
!gainz not working with just my RS account

### ISSUE THREAD

**Issue by DaanV1** [WittyPleb/RuneCord#19]
!gainz doesn't work with my username and my username only. It works for all of my friends accounts plus some random ones too. Mine doesn't, it shows only 0 xp gained.
I have my Adventures log set to public (been like that for three years) and RuneTrack has been tracking since 2013.

**Reproduction Steps:**

1. type !gainz Daan V

**Expected behavior:**
Shows table of nothing gained when I've been playing all day.

**Observed behavior:**

.Shows table of nothing gained when I've been playing all day.

**Screenshots and GIFs**

![nothing](https://cloud.githubusercontent.com/assets/24628127/21290247/7550db94-c4b3-11e6-9583-b2c55f52c7a2.PNG)

**Bot version: 4.2.4** [Enter Bot version here]
**Local or Official: Official** [Enter local for your own bot, Official for the official bot]

**Additional information:**

* Problem started happening recently, didn't happen in an older version of RuneCord: [Don't know, only tested 4.2.4]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes!]

**Comment by WittyPleb** [comment]
`!gainz` command isn't in the RuneCord bot.
