### ISSUE TITLE
RuneCord Update

### ISSUE THREAD

**Issue by ghost** [WittyPleb/RuneCord#22]
"OUT OF DATE  A new version of RuneCord is available"

Ok to I get the message shown above in the console. I've gone through the documentation and haven't really found much on the subject. Is there a script I can execute to update the bot? 

What I'm really asking here is if theres an easy method of updating the bot.

**Comment by WittyPleb** [comment]
You can update the bot by re-downloading the files in the 'Releases' area,
and you just replace all the files.

Link here: https://github.com/unlucky4ever/RuneCord/releases

**Comment by ghost** [comment]
:/ Was afraid you'd say that, thanks.
