### ISSUE TITLE
~alog Command not Working

### ISSUE THREAD

**Issue by ghost** [WittyPleb/RuneCord#25]
I run the alog command with a valid user and it responds with "There was an error while grabbing the adventurer's log for '<user>'. Please try again later."

**Comment by Zilpherest** [comment]
Hi. I just tested the command myself, and it seems to be working fine. Did you happen to accidentally misspell the persons username?

**Comment by ghost** [comment]
Can you give me a test username to try?

**Comment by Zilpherest** [comment]
Sure, try Zezima. He's quite well known and should definitely have an Adventurers log. Also, the person you're looking up has to have their privacy set to Public on their Rune Metrics profile.

**Comment by ghost** [comment]
It still give me an error :( https://gyazo.com/563aae24ef5dbad1feadb8fdc77c344a.png

**Comment by Zilpherest** [comment]
It seems like Zezima's profile is set to private. Try my username, TeddyPony. That one works.

**Comment by ghost** [comment]
Oh okay. Let me try.

**Comment by ghost** [comment]
It works thank you! I was trying profiles that were private (silly me) thank you for your help!

**Comment by Zilpherest** [comment]
No problem :) Glad I could help solve the problem.
