### ISSUE TITLE
Warbands time is off

### ISSUE THREAD

**Issue by 2spook5me** [WittyPleb/RuneCord#7]
The next wbs is in 26 minutes as I am typing this, but the bot keeps telling me it's 5 hours and 26 minutes. 
Not sure if the latest update screwed this over or what.

**Comment by WittyPleb** [comment]
Seems the way warbands is done has changed, I've disabled the command until further notice.

**Comment by WittyPleb** [comment]
Forgot to resolve this when I fixed it, but it's resolved.
